Roadmap to DL added
IvLabs/resources pull request #18
Opened 2020-04-30 19:51 UTC by take2rohit

Please review this. 
If small changes are there modify and merge it, please.

2020-05-01 04:58 UTC, SharathRaparthy commented on deep-learning/README.md
>  ### Roadmap to Deep Learning with Images
Deep learning with images sounds weird. Instead, write something like "Roadmap to deep learning for perception/vision"

2020-05-01 05:06 UTC, SharathRaparthy commented on deep-learning/README.md
> +1. Get started with [Introduction to Computer Vision](https://www.udacity.com/course/introduction-to-computer-vision--ud810) to get an idea of how Image Processing and Computer Vision works. You can
Maybe you can improve the sentence formation. Write something like this "Before jumping to learning-based techniques for vision; it is recommended to go through some of the fundamental concepts of computer vision. From our experience, we found [Introduction to Computer Vision](https://www.udacity.com/course/introduction-to-computer-vision--ud810) is a good starting point, and it covers some concepts like (name two or three concepts).

2020-05-01 05:10 UTC, SharathRaparthy commented on deep-learning/README.md
> +2. Once you get the hang of Computer Vision, you can start revising basic Linear Algebra alongside. You should atleast have knowledge of maths taught till 1st year of engineering (concepts like diffe
This sentence is more or less like ordering. Write something along these lines.
Once you get a hang on computer vision concepts, it is advisable to go through some of the linear algebra concepts as well. Some of them include eigendecomposition, single value decomposition, matrix and vector norms (and other imp concepts. Refer Ian Goodfellow's textbook for more references). 

It's always good to be more specific and being abstract (like linear alebra)

2020-05-01 05:12 UTC, SharathRaparthy commented on deep-learning/README.md
> +3. It is assumed that you know Python. If not, then go through some tutorials like [this one by Corey Schafer](https://www.youtube.com/watch?v=YYXdXT2l-Gg&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU).
Nah! CHange this sentence.

2020-05-01 05:13 UTC, SharathRaparthy requested changes
Please make changes

2020-05-02 11:44 UTC, kartikpaigwar commented on deep-learning/README.md
> +### Roadmap to Deep Learning with Images
You can say Deep Learning for Visual Recognition. Perception is a bigger category. Prerequisites will change accordingly.

2020-05-02 12:03 UTC, kartikpaigwar commented on deep-learning/README.md
> +1. Get started with [Introduction to Computer Vision](https://www.udacity.com/course/introduction-to-computer-vision--ud810) to get an idea of how Image Processing and Computer Vision works. You can
See, if one's focus is to use deep learning for object detection, segmentation (feature level understanding) etc, then understanding only Image Processing is sufficient.  [Digital image processing by Rafael C. Gonzalez](http://web.ipac.caltech.edu/staff/fmasci/home/astro_refs/Digital_Image_Processing_2ndEd.pdf) is a standard book to refer. If one's focusing on deep learning for Computer Vision/Perception application then Image Processing and complete course on Introduction to Computer Vision is requisite. Perception includes concepts of 3D perspective, Stereo, Optical flow, object tracking, visual recognition etc which are all very important. In simple words, Image Processing is kinematics and Computer Vision is dynamics.

2020-05-03 14:33 UTC, take2rohit reviewed
Changes are done according to @SharathRaparthy and @kartikpaigwar
Feel free to reopen if there are any errors

2020-05-03 15:00 UTC, merged