Addition of New Repo Folder - Computer Vision
IvLabs/resources pull request #19
Opened 2020-05-17 16:46 UTC by FlagArihant2000

Listed the basic courses that are required to get the basic idea of computer vision techniques, followed by other lecture series, lecture notes, books and publications that one might use to assist them with their project.

2020-05-17 18:13 UTC, take2rohit commented
I would request @aj161198 to verify the content and @akshaykvnit to check for grammatical error. Thanks.

2020-05-17 18:51 UTC, akshaykvnit commented on computer-vision/README.md
> +1. To learn basic concepts that are used in image processing and computer vision, [Introduction to Computer Vision](https://www.udacity.com/course/introduction-to-computer-vision--ud810) is a good pl
because this is a long paragraph. Keep the first sentence in 1. and the remaining parts in a, b, c, ... under the 1.

2020-05-17 18:51 UTC, akshaykvnit commented on computer-vision/README.md
> +2. For discussing the feature detection and matching techniques, one can have a look at the [documentation](https://docs.opencv.org/3.4.2/db/d27/tutorial_py_table_of_contents_feature2d.html) provided
use capital P in Python.

2020-05-17 18:52 UTC, akshaykvnit commented on computer-vision/README.md
> +2. For implementation of some of the concepts, [OpenCV](https://opencv.org/releases/) will help you. Note that you are required to have some background in python. There are many tutorials available,
use capital P in Python

2020-05-17 19:58 UTC, kartikpaigwar requested changes

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +# Computer Vision
Add Image Processing Resources separately in the same before CV.

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +The repository shall focus on the traditional aspects of computer vision, particularly multiview geometry.
use present tense

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +1. It is expected that one is familiar with some of the concepts of Linear Algebra. No course can beat the one provided by [Gilbert Strang](https://www.youtube.com/playlist?list=PLE7DDD91010BC51F8).
Please use formal language. This is not a competition between the courses.

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +## Pre - Requisites
Image Processing is the main prerequisite. Move to CV after having an overview of IP.

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +2. For implementation of some of the concepts, [OpenCV](https://opencv.org/releases/) will help you. Note that you are required to have some background in python. There are many tutorials available,
Python isn't an obligation, one can implement in C++ too. Such notes are not required. Keep some stuff Self-Explanatory.  Put OpenCV in Libraries for Implementation.

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +1. To learn basic concepts that are used in image processing and computer vision, [Introduction to Computer Vision](https://www.udacity.com/course/introduction-to-computer-vision--ud810) is a good pl
Introduction to Computer Vision by udacity has a refresher for Image Processing but hasn't covered everything. Don't recommend this course for Image Processing. This course is mainly focused on CV. This should be put into the main course section.

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +3. [Digital image processing, Rafael C. Gonzalez](http://web.ipac.caltech.edu/staff/fmasci/home/astro_refs/Digital_Image_Processing_2ndEd.pdf)
A fundamental book for IP.
And a fundamental video lecture series for Image and video processing: https://www.youtube.com/watch?v=bxhJEe38bhY&list=PLZ9qNFMHZ-A79y1StvUUqgyL-O0fZh2rs

2020-05-17 19:58 UTC, kartikpaigwar commented on computer-vision/README.md
> +4. [Computer Vision by Mubarak Shah, University of Central Florida](https://www.youtube.com/playlist?list=PLd3hlSJsX_Imk_BPmB_H3AQjFKZS9XgZm)
This course is also an Intro to CV. Make Intro to CV course section and put udacity and Mubarak shah course in that

2020-05-18 12:37 UTC, kartikpaigwar approved these changes

2020-05-19 23:15 UTC, take2rohit commented
Merging it due to its inactivity and also it seems complete by now. 
Feel free to reopen or revert this PR in case of any changes.

2020-05-19 23:15 UTC, merged